module.exports = {	
	TITLE_MIN_LENGTH: 3,
	TITLE_MAX_LENGTH: 50,
	DESCRIPTION_MIN_LENGTH: 50,
	DESCRIPTION_MAX_LENGTH: 255,
	INGRIDIENT_MIN_LENGTH: 3,
	INGRIDIENT_MAX_LENGTH: 25,
	DIRECTION_MIN_LENGTH: 3,
	DIRECTION_MAX_LENGTH: 255,
	INGRIDIENTS_MIN_AMOUNT: 1,
	DIRECTIONS_MIN_AMOUNT: 1,
	COOKING_MIN_LENGTH: 5
};
